#!/bin/bash
# Requirements: clockify-cli, fzf, gum
#Custom script to work with clockify-cli
# SHOULD work to easily create a task for me, maybe stop it later

SELECTION=$(cat ~/.local/bin/clocky-cli/projects | fzf --prompt='PROJECT > ')
[ -z "$SELECTION" ] && exit 0
PROJECT=$(echo "$SELECTION" | cut -d'|' -f1 | sed 's/ *$//')
CLIENT=$(echo "$SELECTION" | cut -d'|' -f2 | sed 's/^ *//')
DESCRIPTION=$(gum input --prompt="Descripción > ")
[ -z "$DESCRIPTION" ] && exit 0
TAG=$(cat ~/.local/bin/clocky-cli/tags | fzf --prompt='Tag (press Esc if no tag) > ')

# Debug print
#printf "clockify-cli in --description '$DESCRIPTION' --project '$PROJECT' --client '$CLIENT' --tag '$TAG' $*"
clockify-cli in --description "$DESCRIPTION" --project "$PROJECT" --client "$CLIENT" --tag "$TAG" --interactive=0 "$*"
